server:
  port: 9000

spring:
  application.name: givro
  main.show_banner: false
  profiles.active: development
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none

flyway.locations: classpath:db/migration

---

spring:
  profiles: development
  datasource:
    url: jdbc:hsqldb:file:build/db/app-db
    username: sa
    driverClassName: org.hsqldb.jdbc.JDBCDriver

---

spring:
    profiles: production
